### PR TITLE
added DLLFILES subdirectory check

### PR DESCRIPTION
**Pull request by ayoungpe**
For compatibility with REFPROP v10.

### CODE REVIEW

**Comment by ibell** [comment]
Thanks, you are my hero! This was on my list of things to do and I totally forgot!

**Comment by ayoungpe** [comment]
You're welcome.

Just so I'm clear, is the DLLFILES/PASS_FTN.FOR aliasing still relevant for compiling on Linux?  I understand it enables cross-platform functionality, but I've been getting segmentation faults when accessing the shared library librefprop.so using the Python ctypes module on Ubuntu.

```
>>> from ctypes import *
>>> rp = cdll.LoadLibrary("librefprop.so")
>>> p = c_char_p("~/REFPROP")
>>> rp.SETPATHdll(p)
0
>>> argon = c_char_p("ARGON")
>>> ierr = c_int()
>>> rp.SETFLUIDSdll(a, ierr)
Segmentation fault
```

**Comment by ibell** [comment]
Best to use my Python wrapper :
https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/python

Works fine on all platforms. All the hard work is done for you :)

**Comment by ayoungpe** [comment]
Interesting, can it reference `REFPROP.dll` on Linux, or does it have the ability to use `librefprop.so`?

**Comment by ibell** [comment]
As usual you must use the right shared library for your system, so on
Linux, you'll need to use the shared library you compiled yourself

**Pull request merged**
