### PR TITLE
Debug variables and string length

### PR DESCRIPTION
**Pull request by jowr**
I included more static variables for debugging and for the string length

### CODE REVIEW

**Comment by ibell** [comment]
I know its been a while but shall we merge this PR?

**Comment by jowr** [comment]
I would say so, I do not see any problems.

**Comment by ibell** [comment]
Hmm... I just noticed that this was based on the coverity_scan branch.  Hopefully that's not a major problem...

**Comment by jowr** [comment]
Should no be a problem, coveriy_scan is synced with the master regularly.

**Pull request merged**
